import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Blive",
    description: "Round Neck T-Shirt",
    rating: "4",
    mrp: "999",
    mrpCalculation: "999",
    discountPrice: "199",
    discountPriceCalculation: "199",
    discountPercent: "80",
    img: "https://rukminim2.flixcart.com/image/452/542/kt7jv680/shopsy-t-shirt/x/g/8/xl-skb-try-this-original-imag6hqngemxvfst.jpeg?q=50",
    categoryName: "fashion",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "Levis",
    description: "Printed Black T-Shirt",
    rating: "5",
    mrp: "1299",
    mrpCalculation: "1299",
    discountPrice: "299",
    discountPriceCalculation: "299",
    discountPercent: "76",
    img: "https://rukminim2.flixcart.com/image/452/542/kk8mcnk0/t-shirt/i/j/r/l-t339hs-blwh-new-eyebogler-original-imafzmkyybvqcuht.jpeg?q=50",
    categoryName: "fashion",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "Fortune Oil",
    description: "Refined Sunflower Oil",
    rating: "3",
    mrp: "215",
    mrpCalculation: "215",
    discountPrice: "205",
    discountPriceCalculation: "205",
    discountPercent: "4",
    img: "https://rukminim2.flixcart.com/image/280/280/k7usyvk0/edible-oil/e/t/c/1-sunlite-refined-pouch-sunflower-oil-fortune-original-imafpzwhyyhhvzbk.jpeg?q=70",
    categoryName: "grocery",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "IPhone",
    description: "iPhone 13 Mini",
    rating: "5",
    mrp: "69,999",
    mrpCalculation: "69999",
    discountPrice: "59,999",
    discountPriceCalculation: "59999",
    discountPercent: "14",
    img: "https://rukminim2.flixcart.com/image/312/312/ktketu80/mobile/z/k/a/iphone-13-mini-mlkc3hn-a-apple-original-imag6vp6dzauezvs.jpeg?q=70",
    categoryName: "mobiles",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "Router",
    description: "D-Link Wireless Router",
    rating: "4",
    mrp: "2508",
    mrpCalculation: "2508",
    discountPrice: "1399",
    discountPriceCalculation: "1399",
    discountPercent: "44",
    img: "https://rukminim2.flixcart.com/image/612/612/kg5fzww0pkrrdj/router-refurbished/m/9/h/a-dir-819-d-link-original-imafwjfvpfynagup.jpeg?q=70",
    categoryName: "electronics",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "MarQ TV",
    description: "MarQ 80 cm (32 inch) HD",
    rating: "3",
    mrp: "19,999",
    mrpCalculation: "19999",
    discountPrice: "8,999",
    discountPriceCalculation: "8999",
    discountPercent: "55",
    img: "https://rukminim2.flixcart.com/image/312/312/ktyp8cw0/television/q/r/o/32hdndmsvab-marq-original-imag76pvrgnqhxhu.jpeg?q=70",
    categoryName: "appliances",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "Teddy Bear",
    description: "Purple Color teddy bear",
    rating: "2",
    mrp: "2,999",
    mrpCalculation: "2999",
    discountPrice: "299",
    discountPriceCalculation: "299",
    discountPercent: "90",
    img: "https://rukminim2.flixcart.com/image/612/612/k3xcdjk0/stuffed-toy/b/8/5/adorable-teddy-bear-purple-color-medium-size-3-feet-for-your-original-imafmy5tp9sxpnzz.jpeg?q=70",
    categoryName: "toys",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "Osiris",
    description: "3-Layer Face Mask",
    rating: "4",
    mrp: "1000",
    mrpCalculation: "1000",
    discountPrice: "199",
    discountPriceCalculation: "199",
    discountPercent: "79",
    img: "https://rukminim2.flixcart.com/image/612/612/ktvucnk0/mask-respirator/h/c/w/free-size-100-os-adb-001-100-surgical-mask-osiris-original-imag74ntzqtkfacd.jpeg?q=70",
    categoryName: "masks",
    inWishlist: false,
  },
  {
    _id: uuid(),
    title: "Haldirams",
    description: "Bhujia Sev",
    rating: "5",
    mrp: "199",
    mrpCalculation: "199",
    discountPrice: "99",
    discountPriceCalculation: "99",
    discountPercent: "50",
    img: "https://rukminim2.flixcart.com/image/612/612/kcp4osw0/snack-savourie/j/z/v/200-bhujia-sev-pouch-haldiram-s-original-imaftrryz6hzgyrp.jpeg?q=70",
    categoryName: "snacks",
    inWishlist: false,
  },
];
